apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    team: product
    version: 1.0.1
    environment: development
  annotations:
    description: This is app who made by product team
    myjson: '{"name": "Udin"}'
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80